services:
  backend:
    build: ./backend/wizard-backend
    ports:
      - "5000:5000"
    environment:
      - CLIENT_URL=http://frontend:3000
    volumes:
      - ./backend/wizard-backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend/wizard-frontend
    ports:
    - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/wizard-frontend:/app
      - /app/node_modules
    command: npm start