services:
  backend:
    build: ./backend/wizard-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend/wizard-backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend/wizard-frontend
    ports:
    - "3000:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/wizard-frontend:/app
      - /app/node_modules
    command: npm start
  
  mongo:
    image: mongo:7
    container_name: wizard-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: